python neoabstract.py /data/amazon amazon
python neoabstract.py /data/dangdang dangdang
python neoabstract.py /data/no5 no5
python neoabstract.py /data/guopi guopi
python neoabstract.py /data/2688 2688
python neoabstract.py /data/sasa sasa
#python neoabstract.py /data/360buy 360buy
#python neoabstract.py /data/cntvs cntvs
python neoabstract.py /data/redbaby redbaby
#python neoabstract.py /data/jafei jafei
python neoabstract.py /data/yoyo18 yoyo18
#python neoabstract.py /data/d1 d1
python neoabstract.py /data/yihaodian yihaodian
python neoabstract.py /data/7shop24 7shop24
python neoabstract.py /data/meixiu meixiu
python neoabstract.py /data/m18 m18
python neoabstract.py /data/lafaso lafaso
python neoabstract.py /data/meethall meethall
#python neoabstract.py /data/u9buy u9buy
python neoabstract.py /data/strawberrynet strawberrynet
